/*
 * TVDB API V4
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * OpenAPI spec version: 4.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.tinymediamanager.scraper.thetvdb.entities;

import java.math.BigDecimal;
import java.util.List;

import com.google.gson.annotations.SerializedName;

/**
 * extended artwork record
 */

public class ArtworkExtendedRecord {
  @SerializedName("episodeId")
  public Integer         episodeId       = null;

  @SerializedName("height")
  public Integer         height          = null;

  @SerializedName("id")
  public Long            id              = null;

  @SerializedName("image")
  public String          image           = null;

  @SerializedName("includesText")
  public Boolean         includesText    = null;

  @SerializedName("language")
  public String          language        = null;

  @SerializedName("movieId")
  public Integer         movieId         = null;

  @SerializedName("networkId")
  public Integer         networkId       = null;

  @SerializedName("peopleId")
  public Integer         peopleId        = null;

  @SerializedName("score")
  public BigDecimal      score           = null;

  @SerializedName("seasonId")
  public Integer         seasonId        = null;

  @SerializedName("seriesId")
  public Integer         seriesId        = null;

  @SerializedName("seriesPeopleId")
  public Integer         seriesPeopleId  = null;

  @SerializedName("status")
  public ArtworkStatus   status          = null;

  @SerializedName("tagOptions")
  public List<TagOption> tagOptions      = null;

  @SerializedName("thumbnail")
  public String          thumbnail       = null;

  @SerializedName("thumbnailHeight")
  public Integer         thumbnailHeight = null;

  @SerializedName("thumbnailWidth")
  public Integer         thumbnailWidth  = null;

  @SerializedName("type")
  public Integer         type            = null;

  @SerializedName("updatedAt")
  public Long            updatedAt       = null;

  @SerializedName("width")
  public Integer         width           = null;
}
