/*
 * TVDB API V4
 * Documentation for tvdb api v4
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.tinymediamanager.scraper.thetvdb.entities;

import java.util.List;

import com.google.gson.annotations.SerializedName;

public class Character {
  @SerializedName("aliases")
  public List<Alias>  aliases              = null;

  @SerializedName("episodeId")
  public Integer      episodeId            = null;

  @SerializedName("id")
  public Integer      id                   = null;

  @SerializedName("image")
  public String       image                = null;

  @SerializedName("isFeatured")
  public Boolean      isFeatured           = null;

  @SerializedName("movieId")
  public Integer      movieId              = null;

  @SerializedName("name")
  public String       name                 = null;

  @SerializedName("nameTranslations")
  public List<String> nameTranslations     = null;

  @SerializedName("overviewTranslations")
  public List<String> overviewTranslations = null;

  @SerializedName("peopleId")
  public Integer      peopleId             = null;

  @SerializedName("seriesId")
  public Integer      seriesId             = null;

  @SerializedName("sort")
  public Integer      sort                 = null;

  @SerializedName("type")
  public Integer      type                 = null;

  @SerializedName("url")
  public String       url                  = null;

  @SerializedName("personName")
  public String       personName           = null;

  @SerializedName("peopleType")
  public String       peopleType           = null;
}
