/*
 * TVDB API V4
 * Documentation for tvdb api v4
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.tinymediamanager.scraper.thetvdb.entities;

import java.util.List;

import com.google.gson.annotations.SerializedName;

public class EpisodeExtendedRecord {
  @SerializedName("remoteIds")
  public List<RemoteID>          remoteIDs            = null;

  @SerializedName("aired")
  public String                  aired                = null;

  @SerializedName("airsAfterSeason")
  public Integer                 airsAfterSeason      = null;

  @SerializedName("airsBeforeEpisode")
  public Integer                 airsBeforeEpisode    = null;

  @SerializedName("airsBeforeSeason")
  public Integer                 airsBeforeSeason     = null;

  @SerializedName("awards")
  public List<AwardBaseRecord>   awards               = null;

  @SerializedName("characters")
  public List<Character>         characters           = null;

  @SerializedName("contentRatings")
  public List<ContentRating>     contentRatings       = null;

  @SerializedName("id")
  public Integer                 id                   = null;

  @SerializedName("image")
  public String                  image                = null;

  @SerializedName("imageType")
  public Integer                 imageType            = null;

  @SerializedName("isMovie")
  public Integer                 isMovie              = null;

  @SerializedName("name")
  public String                  name                 = null;

  @SerializedName("nameTranslations")
  public List<String>            nameTranslations     = null;

  @SerializedName("companies")
  public List<CompanyBaseRecord> companies            = null;

  @SerializedName("overviewTranslations")
  public List<String>            overviewTranslations = null;

  @SerializedName("productionCode")
  public String                  productionCode       = null;

  @SerializedName("runtime")
  public Integer                 runtime              = null;

  @SerializedName("seasons")
  public List<SeasonBaseRecord>  seasons              = null;

  @SerializedName("seriesId")
  public Integer                 seriesId             = null;

  @SerializedName("tagOptions")
  public List<TagOption>         tagOptions           = null;

  @SerializedName("trailers")
  public List<Trailer>           trailers             = null;

  @SerializedName("number")
  public Integer                 episodeNumber        = null;

  @SerializedName("seasonNumber")
  public Integer                 seasonNumber         = null;
}
