stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .ci/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  image: registry.gitlab.com/tinymediamanager/docker/packaging:20220601182613
  environment:
    name: prerelease
    url: https://prerelease.tinymediamanager.org
  allow_failure: false
  variables:
    PURGE_CF_CACHE: 'curl -X POST https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache -H "Content-Type: application/json" -H "Authorization:Bearer $CF_BEARER" --data "{\"purge_everything\":true}"'
  script:
    # package
    - mvn $MAVEN_CLI_OPTS -P gitlab-ci -P dist -DbuildNumber=${CI_COMMIT_SHORT_SHA} -Dgetdown=getdown-prerelease.txt -Dtear=prerelease -Dthread_pool_size=1 clean package

    # build windows installer
    - chmod 777 . dist
    - sudo -u xclient PATH=$PATH:/opt/bin AppBundler/create_windows_installer.sh

    # build macOS dmg file
    - sh AppBundler/create_dmg.sh

    # push the build to the webserver
    - lftp -c "set ftp:ssl-allow no; open -u ${FTP_USER_PREREL},${FTP_PASSWORD_PREREL} ${FTP_HOST}; mirror -Rev target/tinyMediaManager-getdown/ ./upload/v5/build; mirror -Rev dist/ ./upload/v5/dist; chmod -R g+w ./upload/v5"

    # and publish the files on the webserver
    - curl https://prerelease.tinymediamanager.org/${PUBLISH_ENDPOINT_V5}
    - curl https://prerelease.tinymediamanager.org/${CREATE_INDEX_V4}
    - curl https://prerelease.tinymediamanager.org/${CREATE_INDEX_V5}

    # purge CF cache
    - 'eval "$PURGE_CF_CACHE"'

  artifacts:
    expire_in: 2 days
    paths:
      - dist/tmm*linux-amd64.tar.gz # upload for docker build

deploy-docker:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
  needs:
    - build
  variables:
    IMAGE_NAME: tinymediamanager/tinymediamanager:4-prerelease
  script:
    # login
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

    # build
    - tar xzf dist/tmm*linux-amd64.tar.gz -C docker/
    - cd docker
    - docker build -f Dockerfile.prerelease -t $IMAGE_NAME .

    # push to the registry
    - docker push $IMAGE_NAME
