# Building application container
FROM max06net/base-gui:0.0.1

ENV APP=tinyMediaManager

ARG LIBZEN=https://mediaarea.net/download/binary/libzen0/0.4.39/libzen0v5_0.4.39-1_amd64.Debian_10.deb
ARG LIBMEDIAINFO=https://mediaarea.net/download/binary/libmediainfo0/21.03/libmediainfo0v5_21.03-1_amd64.Debian_10.deb

# Install requirements for TMM
ADD ../dist /tmp/dist
RUN \
    apt-get update && \
    apt-get install --no-install-recommends -y \
        wget \
        ca-certificates \
        libcurl3-gnutls \
        libmms0 \
        ffmpeg \
        yad && \
    wget -q ${LIBZEN} && \
    wget -q ${LIBMEDIAINFO} && \
    dpkg -i *.deb && \
    tar xzf /tmp/dist/tmm*linux*.tar.gz -C /tmp/ && \
    mv /tmp/tinyMediaManager/* /app/ && \
    rm -R /tmp/dist /tmp/tinyMediaManager && \
    mkdir -p /data/data && \
    # Remove some unneeded stuff.
    rm *.deb && \
    rm -rf /var/lib/apt/lists/* 

ADD launcher-extra.yml /app/
ADD tmm.prop /data/data/

LABEL Name="tinyMediaManager test build" Version="v4"

WORKDIR /app
CMD ["/app/tinyMediaManager"]
