module org.tinymediamanager {
  requires kotlin.stdlib;
  requires org.apache.commons.lang3;
  requires java.desktop;
  requires org.apache.commons.io;
  requires org.slf4j;
  requires miglayout.swing;
  requires betterbeansbinding.core;
  requires com.h2database.mvstore;
  requires com.fasterxml.jackson.databind;
  requires glazedlists;
  requires org.joda.time;
  requires org.apache.commons.text;
  requires logback.classic;
  requires logback.core;
  requires info.picocli;
  requires com.fasterxml.jackson.dataformat.yaml;
  requires loop.fs.iso.impl;
  requires loop.fs.udf.impl;
  requires com.sun.jna;
  requires kodi.json.rpc;
  requires betterbeansbinding.swingbinding;
  requires tmdb.java;
  requires jmte;
  requires com.formdev.flatlaf;
  requires imgscalr.lib;
  requires animated.gif.lib;
  requires cling.core;
  requires com.kitfox.svg;
  requires java.logging;
  requires license;
  requires gson;
  requires okhttp3.logging;
  requires retrofit2;
  requires retrofit2.converter.gson;
  requires org.apache.commons.codec;
  requires org.jsoup;
  requires okhttp3;
  requires okio;
  requires trakt.java;
  requires org.threeten.bp;
  requires thetvdb.java;
  requires cling.support;
  requires seamless.util;
  requires nanohttpd;
  requires yt;
  requires jtidy.r938;
  requires org.apache.commons.compress;
  requires aXMLRPC;
  requires dec;
  requires muxer;
  requires isoparser;
  requires commons.csv;
  requires getdown.core;
  requires jul.to.slf4j;
  requires java.sql;

  uses org.tinymediamanager.scraper.spi.IAddonProvider;

  exports org.tinymediamanager.scraper;
  exports org.tinymediamanager.scraper.config;
  exports org.tinymediamanager.scraper.entities;
  exports org.tinymediamanager.scraper.exceptions;
  exports org.tinymediamanager.scraper.interfaces;
  exports org.tinymediamanager.scraper.http;
  exports org.tinymediamanager.scraper.spi;
  exports org.tinymediamanager.scraper.util;
  
  // open parts of tmm to other modules
  opens org.tinymediamanager.core to com.fasterxml.jackson.databind, glazedlists, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.core.entities to com.fasterxml.jackson.databind, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.core.movie to com.fasterxml.jackson.databind, org.apache.commons.lang3,betterbeansbinding.core;
  opens org.tinymediamanager.core.movie.entities to com.fasterxml.jackson.databind, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.core.movie.connector to com.fasterxml.jackson.databind;
  opens org.tinymediamanager.core.movie.filenaming to com.fasterxml.jackson.databind;
  opens org.tinymediamanager.core.tvshow to com.fasterxml.jackson.databind, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.core.tvshow.entities to com.fasterxml.jackson.databind, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.core.tvshow.connector to com.fasterxml.jackson.databind;
  opens org.tinymediamanager.core.tvshow.filenaming to com.fasterxml.jackson.databind;
  opens org.tinymediamanager.scraper to org.apache.commons.lang3;
  opens org.tinymediamanager.ui to com.fasterxml.jackson.databind, org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.ui.components to betterbeansbinding.core, java.desktop;
  opens org.tinymediamanager.ui.panels to betterbeansbinding.core;
  opens org.tinymediamanager.ui.movies to org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.ui.movies.dialogs to betterbeansbinding.core;
  opens org.tinymediamanager.ui.moviesets to org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.ui.moviesets.dialogs to betterbeansbinding.core;
  opens org.tinymediamanager.ui.tvshows to org.apache.commons.lang3, betterbeansbinding.core;
  opens org.tinymediamanager.ui.tvshows.dialogs to betterbeansbinding.core;

  opens org.tinymediamanager.ui.components.combobox;
  opens org.tinymediamanager.ui.components.datepicker;
  opens org.tinymediamanager.ui.components.table;
  opens org.tinymediamanager.ui.components.tree;
  opens org.tinymediamanager.ui.components.toolbar;
  opens org.tinymediamanager.ui.components.treetable;
  opens org.tinymediamanager.ui.plaf;
  opens org.tinymediamanager.ui.plaf.light;
  opens org.tinymediamanager.ui.plaf.dark;
}
